matrix:
  include:
  - stage: Tox Test
    name: "Unit Tests"
    language: python
    sudo: required
    dist: xenial
    python: 3.7
  install: pip install tox-travis
  script: tox
- stage: Cypress Test
  name: "End to End testing Cypress"
  language: node_js
  node_js:
    - 10
  cache:
    npm: true
    directories:
      - ~/.npm
      - ~/.cache
      - node_modules
    node_js:
      - '8'
  install:
    - cd src/main/vue
    - npm ci
  script:
    - npm run cy:run