python: 3.7
node_js: 10

matrix:
  include:
  - stage: Tox Test
    name: "Unit Tests"
    language: python
    sudo: required
    dist: xenial
    python: 3.7
    install: pip install tox-travis
    script: tox
  - stage: Cypress Test
    name: "Cypress UI Test"
    language: node_js
    node_js: 10
    npm: true
    directories:
    - /.npm
    - /.cache
    - node_modules
    before_install:
    - sudo apt-get -y install python3-pip python-dev
    - sudo pip3 install -U setuptools
    - sudo pip install Flask
    - sudo pip install flask-cors
    - python3 -V
    - pip3 -V
    install:
    - npm install
    - sudo pip3 install -r requirements
    - cd src/main/python/client/frontend/src/router
    - npm ci
    before_script:
    - npm run dev &
    - python ../../../../server/rest.py &
    script:
    - cd ..
    - cd ..
    - cd ..
    - cd ..
    - cd ..
    - cd ..
    - cd ui_tests
    - $(npm bin)/cypress run