python: 3.7

matrix:
  include:
  - stage: Tox Test
    name: "Unit Tests"
    language: python
    sudo: required
    dist: xenial
    python: 3.7
    install: pip install tox-travis
    script: tox
